name: hapis1
base: core18
version: '1.0.11'
summary: Hapi Server Linux-x64
description: |
  Hapi Server Linux-x64
grade: devel
confinement: devmode

apps:
  curl:
    command: curl
  bash:
    command: bash
  hapis1:
    command: /snap/hapis1/current/hapi-server-v1.0.11/bin/node /snap/hapis1/current/hapi-server-v1.0.11/test/server-test.js 

  

parts:
  hapis1:
    source: https://github.com/drunkenlord/sna-test-1/releases/download/v1.0/hapi-server-v1.0.11.tar.gz
    plugin: dump
  curl:
    source: http://curl.haxx.se/download/curl-7.45.0.tar.bz2
    plugin: autotools
  gnu-bash:
    source: http://ftp.gnu.org/gnu/bash/bash-4.3.tar.gz
    plugin: autotools